Очень быстро спрашивали про два исключения одновременно сразу.

В Rust уже пишут не `try!(foo())`, а `foo()?`

`tl::expected` может быть лучшим аналогом.
